spring:
  application:
    name: JavaMailSender
  mail:
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: mailadresiniz
    password: uygulamaparolanız
    port: 587
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaMailSender
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080